### ISSUE TITLE
Refactor the project to support OpenJDK 11

### ISSUE THREAD

**Issue by bigdata-memory** [apache/mnemonic#131]
I recall the similar issue has been submitted before, but we lost our issue history, so I re-submit it as a top-level ticket that should break down into several sub tasks to fulfill. it could be a milestone if OpenJDK11 is supported.

**Comment by yzz127** [comment]
I think we may need to update this issue as our current target is to support JDK14 instead of version 11

**Comment by yzz127** [comment]
JDK14 upgrade is done, and this issue is no longer valid

**Comment by bigdata-memory** [comment]
I agree, thank you for tracking this.
