### ISSUE TITLE
Fix all test cases after JDK 14 upgrade

### ISSUE THREAD

**Issue by yzz127** [apache/mnemonic#220]
Due to the recent JDK 14 upgrade, not all test cases can run smoothly. We need to review and fix all the test cases in our next release (target 0.16.0)

**Comment by yzz127** [comment]
It seems we have most of the bugs fixed targeting for our 0.16.0 release. @bigdata-memory could you please review if there is any other test cases that need to get fixed? Thanks!

**Comment by bigdata-memory** [comment]
Let's close it here and submit issue in Apache JIRA if any, thanks.
